services:
  - type: web
    name: laravel-backend
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    buildCommand: ""   # queda vacío, porque Dockerfile ya hace todo
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:TU_APP_KEY_REAL
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false

      # si usas base de datos externa:
      # - key: DB_CONNECTION
      #   value: mysql
      # - key: DB_HOST
      #   value: tu-host
      # - key: DB_PORT
      #   value: "3306"
      # - key: DB_DATABASE
      #   value: tu-db
      # - key: DB_USERNAME
      #   value: tu-usuario
      # - key: DB_PASSWORD
      #   value: tu-password
