services:
  - type: web
    name: laravel-backend
    env: docker
    region: oregon  # o la región que prefieras
    plan: free
    branch: main
    dockerfilePath: backend/Dockerfile  # Apunta a la ubicación correcta del Dockerfile
    dockerContext: backend  # Contexto de Docker también en la carpeta backend

    buildCommand: ""  # vacío porque ya está configurado en el Dockerfile
    startCommand: ""  # Laravel servirá desde Apache, ya configurado

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_KEY
        value: base64:TU_APP_KEY  # reemplázalo por tu APP_KEY real

      - key: FIREBASE_CREDENTIALS_JSON
        sync: false  # lo cargas desde el panel web por seguridad

      # si usas base de datos externa:
      # - key: DB_CONNECTION
      #   value: mysql
      # - key: DB_HOST
      #   value: tu-host
      # - key: DB_PORT
      #   value: "3306"
      # - key: DB_DATABASE
      #   value: tu-db
      # - key: DB_USERNAME
      #   value: tu-usuario
      # - key: DB_PASSWORD
      #   value: tu-password
