services:
  - type: web
    name: laravel-backend
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: Dockerfile        # Esto est치 bien porque el Dockerfile est치 en "backend"
    dockerContext: .                  # Ahora el contexto debe ser la carpeta "backend"

    buildCommand: ""  # Ya est치 definido en el Dockerfile
    startCommand: ""  # Laravel servir치 desde Apache, ya configurado

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_KEY
        value: base64:TU_APP_KEY  # Reemplazar con tu APP_KEY real
